name: Tag new releases
on:
  push:
    paths:
      - 'package.json'
    branches:
      - main
jobs:
  tag-release:
    name: Tag new releases
    runs-on: ubuntu-latest

    outputs:
      successful: ${{ steps.create_tag.outputs.successful }}
      version: ${{ steps.create_tag.outputs.version }}

    steps:
      - uses: actions/checkout@v2

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          package-path: ./package.json

      - name: Generate changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@main
        if: steps.create_tag.outputs.successful
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - uses: actions/create-release@v1
        if: steps.create_tag.outputs.successful
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.version }}
          release_name: ${{ steps.create_tag.outputs.version }}
          body: |
            ${{ steps.changelog.outputs.compareurl || '' }}

            ${{ steps.changelog.outputs.changelog || '' }}

  call-deploy:
    needs: tag-release
    uses: ./.github/workflows/deploy-image.yml
    if: ${{ needs.tag-release.outputs.successful }}
    with:
      environment: prod
      version: ${{ needs.tag-release.outputs.version }}
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID_PROD: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
      AWS_SECRET_ACCESS_KEY_PROD: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}

  call-infra:
    needs: [tag-release, call-deploy]
    uses: ./.github/workflows/deploy-infra.yml
    if: ${{ needs.tag-release.outputs.successful }}
    with:
      environment: prod
      apply: true
      version: ${{ needs.tag-release.outputs.version }}
    secrets:
      GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID_PROD: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
      AWS_SECRET_ACCESS_KEY_PROD: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
      NEW_RELIC_INSERT_API_KEY: ${{ secrets.NEW_RELIC_INSERT_API_KEY }}
      INGESTION_API_KEY_PROD: ${{ secrets.INGESTION_API_KEY_PROD }}
